# Generated by Django 6.0.7 on 2026-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_course_price_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
